// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with elevated access - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get('Authorization') === `Bearer ${supabaseKey}`
    ) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);

    return fetch(input, {
      ...init,
      headers,
    });
  };
}

function readSecretKeyMap(value: string | undefined): string | undefined {
  if (!value) {
    return undefined;
  }

  try {
    const parsed = JSON.parse(value) as Record<string, unknown>;

    if (typeof parsed['default'] === 'string' && parsed['default']) {
      return parsed['default'];
    }

    return Object.values(parsed).find(
      (candidate): candidate is string =>
        typeof candidate === 'string' && candidate.length > 0,
    );
  } catch {
    return undefined;
  }
}

function getSupabaseSecretKey(): string | undefined {
  /*
   * Current Supabase environments use SUPABASE_SECRET_KEYS
   * (a JSON map) or SUPABASE_SECRET_KEY.
   *
   * SUPABASE_SERVICE_ROLE_KEY is the legacy variable.
   * Keep it as a fallback for older environments.
   */
  return (
    process.env['SUPABASE_SECRET_KEY'] ||
    readSecretKeyMap(process.env['SUPABASE_SECRET_KEYS']) ||
    process.env['SUPABASE_SERVICE_ROLE_KEY']
  );
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env['SUPABASE_URL'];
  const SUPABASE_SECRET_KEY = getSupabaseSecretKey();

  if (!SUPABASE_URL || !SUPABASE_SECRET_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SECRET_KEY
        ? [
            'Supabase server secret (SUPABASE_SECRET_KEY, SUPABASE_SECRET_KEYS, or SUPABASE_SERVICE_ROLE_KEY)',
          ]
        : []),
    ];

    const message =
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      'Connect Supabase in Lovable Cloud.';

    console.error(`[Supabase] ${message}`);

    throw new Error(message);
  }

  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_SECRET_KEY,
    {
      global: {
        fetch: createSupabaseFetch(
          SUPABASE_SECRET_KEY,
        ),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );
}

let _supabaseAdmin:
  | ReturnType<typeof createSupabaseAdminClient>
  | undefined;

// Server-side Supabase client with elevated access - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations.
// Never expose the server secret to client code.
export const supabaseAdmin = new Proxy(
  {} as ReturnType<typeof createSupabaseAdminClient>,
  {
    get(_, prop, receiver) {
      if (!_supabaseAdmin) {
        _supabaseAdmin =
          createSupabaseAdminClient();
      }

      return Reflect.get(
        _supabaseAdmin,
        prop,
        receiver,
      );
    },
  },
);